const gameCollections = [
    {
        name: "Architects of the West Kingdom",
        buydate: "2019-02-10",
        buycurrency: "USD",
        buyprice: 48.67,
        selldate: "2020-01-05",
        sellcurrency: "SGD",
        sellprice: 38,
        playcount: 8,
        },
        {
        name: "Ares Expedition",
        buydate: "2021-03-03",
        buycurrency: "SGD",
        buyprice: 70.5,
        selldate: "2022-08-08",
        sellcurrency: "SGD",
        sellprice: 50,
        playcount: 11,
        },
        {
        name: "Arkham Horror The Card Game",
        buydate: "2017-09-14",
        buycurrency: "SGD",
        buyprice: 220,
        selldate: "2018-03-16",
        sellcurrency: "SGD",
        sellprice: 185,
        playcount: 8,
        },
        {
        name: "Betrayal at the House on the Hill",
        buydate: "2015-11-15",
        buycurrency: "USD",
        buyprice: 39,
        selldate: "2017-08-14",
        sellcurrency: "SGD",
        sellprice: 38,
        playcount: 5,
        },
        {
        name: "Big Book of Madness",
        buydate: "2016-11-28",
        buycurrency: "SGD",
        buyprice: 40,
        selldate: "2017-06-13",
        sellcurrency: "SGD",
        sellprice: 36,
        playcount: 3,
        },
        {
        name: "Blood Rage + 5th player expansion",
        buydate: "2017-11-11",
        buycurrency: "SGD",
        buyprice: 92.535232,
        selldate: "2018-03-16",
        sellcurrency: "SGD",
        sellprice: 90,
        playcount: 2,
        },
        {
        name: "Bloodborne Board Game",
        buydate: "2019-08-01",
        buycurrency: "SGD",
        buyprice: 323.53,
        selldate: "2021-10-12",
        sellcurrency: "SGD",
        sellprice: 190,
        playcount: 15,
        },
        {
        name: "Brew Crafters",
        buydate: "2020-11-11",
        buycurrency: "SGD",
        buyprice: 49.66,
        selldate: "2021-03-17",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 2,
        },
        {
        name: "Canvas",
        buydate: "2020-06-20",
        buycurrency: "SGD",
        buyprice: 70,
        selldate: "2021-06-11",
        sellcurrency: "SGD",
        sellprice: 50,
        playcount: 2,
        },
        {
        name: "Cartographers Heroes",
        buydate: "2020-11-06",
        buycurrency: "SGD",
        buyprice: 76,
        selldate: "2021-10-24",
        sellcurrency: "SGD",
        sellprice: 76,
        playcount: ,
        },
        {
        name: "Chocolate Factory",
        buydate: "2019-11-26",
        buycurrency: "SGD",
        buyprice: 63.12,
        selldate: "2020-06-17",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 2,
        },
        {
        name: "Chronicles of Crime",
        buydate: "2018-03-21",
        buycurrency: "SGD",
        buyprice: 120.8,
        selldate: "2019-08-10",
        sellcurrency: "SGD",
        sellprice: 88,
        playcount: 16,
        },
        {
        name: "Chronicles of Drunagor",
        buydate: "2021-06-27",
        buycurrency: "SGD",
        buyprice: 205.54,
        selldate: "2021-11-12",
        sellcurrency: "SGD",
        sellprice: 100,
        playcount: 54,
        },
        {
        name: "Circadians Chaos Order",
        buydate: "2022-09-05",
        buycurrency: "NZD",
        buyprice: 75,
        selldate: "2023-03-08",
        sellcurrency: "SGD",
        sellprice: 70,
        playcount: 1,
        },
        {
        name: "Clans of Caledonia",
        buydate: "2019-09-25",
        buycurrency: "USD",
        buyprice: 43.71,
        selldate: "2020-05-20",
        sellcurrency: "SGD",
        sellprice: 47,
        playcount: 10,
        },
        {
        name: "Codenames: Pictures",
        buydate: "2017-02-22",
        buycurrency: "USD",
        buyprice: 16,
        selldate: "2018-07-19",
        sellcurrency: "SGD",
        sellprice: 15,
        playcount: 1,
        },
        {
        name: "Coffee Roaster",
        buydate: "2018-10-15",
        buycurrency: "JPY",
        buyprice: 5510,
        selldate: "2020-12-15",
        sellcurrency: "SGD",
        sellprice: 15,
        playcount: 13,
        },
        {
        name: "Coffee Traders",
        buydate: "2021-07-25",
        buycurrency: "SGD",
        buyprice: 144.03,
        selldate: "2022-02-03",
        sellcurrency: "SGD",
        sellprice: 97,
        playcount: 2,
        },
        {
        name: "Coimbra",
        buydate: "2019-01-18",
        buycurrency: "SGD",
        buyprice: 65,
        selldate: "2019-11-12",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 9,
        },
        {
        name: "Crown of Emara",
        buydate: "2019-08-05",
        buycurrency: "EUR",
        buyprice: 34.79,
        selldate: "2020-03-20",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 5,
        },
        {
        name: "Dead of Winter",
        buydate: "2016-05-04",
        buycurrency: "USD",
        buyprice: 43.5,
        selldate: "2017-05-22",
        sellcurrency: "SGD",
        sellprice: 48,
        playcount: 5,
        },
        #REF!
        {
        name: "Descent: Legends of the Dark",
        buydate: "2021-10-01",
        buycurrency: "SGD",
        buyprice: 193.47,
        selldate: "2022-06-13",
        sellcurrency: "SGD",
        sellprice: 123,
        playcount: 17,
        },
        {
        name: "Dice Hospital + Deluxe",
        buydate: "2020-11-30",
        buycurrency: "SGD",
        buyprice: 119.88,
        selldate: "2021-07-16",
        sellcurrency: "SGD",
        sellprice: 90,
        playcount: 6,
        },
        {
        name: "Diceborn Heroes",
        buydate: "2017-05-25",
        buycurrency: "CAD",
        buyprice: 83,
        selldate: "2021-07-16",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 1,
        },
        {
        name: "Dinosaur World",
        buydate: "2021-10-16",
        buycurrency: "SGD",
        buyprice: 170.63,
        selldate: "2022-03-27",
        sellcurrency: "SGD",
        sellprice: 135,
        playcount: 4,
        },
        {
        name: "Dixit",
        buydate: "2015-10-15",
        buycurrency: "USD",
        buyprice: 25,
        selldate: "2016-10-21",
        sellcurrency: "SGD",
        sellprice: 22,
        playcount: 3,
        },
        {
        name: "Draftosaurus",
        buydate: "2019-12-01",
        buycurrency: "SGD",
        buyprice: 25.35,
        selldate: "2021-03-29",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 10,
        },
        {
        name: "Dune Imperium",
        buydate: "2022-05-14",
        buycurrency: "SGD",
        buyprice: 52,
        selldate: "2023-03-30",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 5,
        },
        {
        name: "Elder Sign",
        buydate: "2015-11-30",
        buycurrency: "SGD",
        buyprice: 35,
        selldate: "2016-11-18",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 5,
        },
        {
        name: "Endeavor Age of Sail",
        buydate: "2021-07-13",
        buycurrency: "SGD",
        buyprice: 75.24,
        selldate: "2021-11-05",
        sellcurrency: "SGD",
        sellprice: 65,
        playcount: 3,
        },
        {
        name: "Escape Plan",
        buydate: "2019-06-01",
        buycurrency: "SGD",
        buyprice: 225.26,
        selldate: "2020-05-29",
        sellcurrency: "SGD",
        sellprice: 116.5,
        playcount: 2,
        },
        #REF!
        {
        name: "Everdell",
        buydate: "2019-11-26",
        buycurrency: "SGD",
        buyprice: 190.25,
        selldate: "2022-03-12",
        sellcurrency: "SGD",
        sellprice: 100,
        playcount: 26,
        },
        {
        name: "Forbidden Desert",
        buydate: "2015-11-24",
        buycurrency: "USD",
        buyprice: 20,
        selldate: "2016-12-02",
        sellcurrency: "SGD",
        sellprice: 28,
        playcount: 5,
        },
        {
        name: "Gloomhaven Forgotten Circles",
        buydate: "2018-05-15",
        buycurrency: "USD",
        buyprice: 25.49,
        selldate: "2020-04-14",
        sellcurrency: "SGD",
        sellprice: 26.5,
        playcount: 0,
        },
        {
        name: "Gloomhaven Jaws of the Lion",
        buydate: "2020-09-01",
        buycurrency: "SGD",
        buyprice: 93.5,
        selldate: "2021-05-20",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 15,
        },
        {
        name: "Grand Austria Hotel",
        buydate: "2018-08-05",
        buycurrency: "SGD",
        buyprice: 50,
        selldate: "2019-02-13",
        sellcurrency: "SGD",
        sellprice: 48,
        playcount: 11,
        },
        {
        name: "Harbour",
        buydate: "2017-11-27",
        buycurrency: "USD",
        buyprice: 15.9696,
        selldate: "2018-08-05",
        sellcurrency: "SGD",
        sellprice: 20,
        playcount: 4,
        },
        {
        name: "Hardback",
        buydate: "2017-04-24",
        buycurrency: "USD",
        buyprice: 36,
        selldate: "2018-03-09",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 1,
        },
        {
        name: "Hokkaido",
        buydate: "2019-02-10",
        buycurrency: "USD",
        buyprice: 26,
        selldate: "2019-07-26",
        sellcurrency: "SGD",
        sellprice: 20,
        playcount: 3,
        },
        {
        name: "IKI",
        buydate: "2019-10-30",
        buycurrency: "JPY",
        buyprice: 4730,
        selldate: "2020-07-27",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 5,
        },
        {
        name: "In the Hall of the Mountain King",
        buydate: "2021-04-22",
        buycurrency: "SGD",
        buyprice: 41,
        selldate: "2021-10-04",
        sellcurrency: "SGD",
        sellprice: 15,
        playcount: 5,
        },
        {
        name: "Isle of Skye",
        buydate: "2017-07-29",
        buycurrency: "SGD",
        buyprice: 30.7,
        selldate: "2018-01-05",
        sellcurrency: "SGD",
        sellprice: 30,
        playcount: 4,
        },
        {
        name: "It's a Wonderful World",
        buydate: "2021-06-01",
        buycurrency: "SGD",
        buyprice: 41.38,
        selldate: "2021-11-27",
        sellcurrency: "SGD",
        sellprice: 30,
        playcount: 5,
        },
        {
        name: "Kanban EV",
        buydate: "2020-02-14",
        buycurrency: "SGD",
        buyprice: 155,
        selldate: "2021-03-01",
        sellcurrency: "SGD",
        sellprice: 155,
        playcount: 0,
        },
        {
        name: "Legendary: A Marvel Deck-building Game",
        buydate: "2017-05-29",
        buycurrency: "SGD",
        buyprice: 74,
        selldate: "2018-03-20",
        sellcurrency: "SGD",
        sellprice: 55,
        playcount: 7,
        },
        {
        name: "Lords of Waterdeep",
        buydate: "2015-10-15",
        buycurrency: "USD",
        buyprice: 36,
        selldate: "2018-07-11",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 10,
        },
        {
        name: "Lords of Waterdeep: Scoundrels of Skullport",
        buydate: "2016-11-13",
        buycurrency: "SGD",
        buyprice: 42,
        selldate: "2017-05-26",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 2,
        },
        {
        name: "Maracaibo",
        buydate: "2020-07-10",
        buycurrency: "USD",
        buyprice: 70.31,
        selldate: "2021-02-23",
        sellcurrency: "SGD",
        sellprice: 60,
        playcount: 7,
        },
        {
        name: "Marco Polo 2",
        buydate: "2020-07-10",
        buycurrency: "USD",
        buyprice: 72.31,
        selldate: "2021-01-01",
        sellcurrency: "SGD",
        sellprice: 90,
        playcount: 4,
        },
        {
        name: "Marvel Champions",
        buydate: "2020-08-12",
        buycurrency: "SGD",
        buyprice: 180,
        selldate: "2020-12-12",
        sellcurrency: "SGD",
        sellprice: 110,
        playcount: 2,
        },
        {
        name: "Merchants Cove",
        buydate: "2021-07-16",
        buycurrency: "SGD",
        buyprice: 175,
        selldate: "2021-11-22",
        sellcurrency: "SGD",
        sellprice: 130,
        playcount: 6,
        },
        {
        name: "Merchants of the Dark Road",
        buydate: "2021-12-17",
        buycurrency: "SGD",
        buyprice: 100.88,
        selldate: "2022-12-17",
        sellcurrency: "SGD",
        sellprice: 75,
        playcount: 6,
        },
        {
        name: "Mice and Mystics",
        buydate: "2015-12-15",
        buycurrency: "USD",
        buyprice: 120,
        selldate: "2016-11-12",
        sellcurrency: "SGD",
        sellprice: 60,
        playcount: 15,
        },
        {
        name: "Middara",
        buydate: "2018-01-05",
        buycurrency: "USD",
        buyprice: 150,
        selldate: "2019-04-18",
        sellcurrency: "USD",
        sellprice: 150,
        playcount: 1,
        },
        {
        name: "Near and Far",
        buydate: "2018-08-05",
        buycurrency: "SGD",
        buyprice: 42.36,
        selldate: "2018-12-06",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 15,
        },
        {
        name: "Nine Tiles Panic",
        buydate: "2019-10-30",
        buycurrency: "JPY",
        buyprice: 2723,
        selldate: "2021-03-29",
        sellcurrency: "SGD",
        sellprice: 27,
        playcount: 13,
        },
        {
        name: "Now or Never",
        buydate: "2021-08-25",
        buycurrency: "USD",
        buyprice: 80,
        selldate: "2022-05-04",
        sellcurrency: "SGD",
        sellprice: 75,
        playcount: 7,
        },
        {
        name: "One Deck Dungeon: Forest of Shadows",
        buydate: "2018-05-12",
        buycurrency: "SGD",
        buyprice: 25.96,
        selldate: "2018-07-09",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 1,
        },
        {
        name: "Orleans + Trade & Intrigue",
        buydate: "2018-11-26",
        buycurrency: "SGD",
        buyprice: 100.29,
        selldate: "2019-05-04",
        sellcurrency: "SGD",
        sellprice: 60,
        playcount: 4,
        },
        {
        name: "Pandemic + On the Brink",
        buydate: "2015-11-24",
        buycurrency: "USD",
        buyprice: 58.44,
        selldate: "2017-12-11",
        sellcurrency: "SGD",
        sellprice: 65,
        playcount: 10,
        },
        {
        name: "Pathfinder ACG",
        buydate: "2016-10-08",
        buycurrency: "SGD",
        buyprice: 160,
        selldate: "2017-03-09",
        sellcurrency: "SGD",
        sellprice: 100,
        playcount: 18,
        },
        {
        name: "Perseverence Castaway Chronicles Ep 1 & 2",
        buydate: "2022-02-01",
        buycurrency: "SGD",
        buyprice: 223.1,
        selldate: "2023-01-09",
        sellcurrency: "SGD",
        sellprice: 172,
        playcount: 3,
        },
        {
        name: "Quadropolis",
        buydate: "2017-02-22",
        buycurrency: "USD",
        buyprice: 42,
        selldate: "2018-01-17",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 7,
        },
        {
        name: "Railroad Ink",
        buydate: "2019-02-24",
        buycurrency: "SGD",
        buyprice: 25.88,
        selldate: "2019-07-04",
        sellcurrency: "SGD",
        sellprice: 22,
        playcount: 2,
        },
        {
        name: "Realm of Sand",
        buydate: "2019-06-26",
        buycurrency: "TWD",
        buyprice: 990,
        selldate: "2020-05-20",
        sellcurrency: "SGD",
        sellprice: 19.5,
        playcount: 6,
        },
        {
        name: "Reavers of Midgard",
        buydate: "2022-01-20",
        buycurrency: "SGD",
        buyprice: 66.808,
        selldate: "2022-06-13",
        sellcurrency: "SGD",
        sellprice: 23,
        playcount: 2,
        },
        {
        name: "Res Arcana + Lux Et Tenebrae",
        buydate: "2020-03-03",
        buycurrency: "SGD",
        buyprice: 83.54,
        selldate: "2020-11-11",
        sellcurrency: "SGD",
        sellprice: 60,
        playcount: 15,
        },
        {
        name: "Rescue Polar Bears",
        buydate: "2019-06-26",
        buycurrency: "TWD",
        buyprice: 1490,
        selldate: "2020-05-15",
        sellcurrency: "SGD",
        sellprice: 36.5,
        playcount: 5,
        },
        {
        name: "Rococo Deluxe",
        buydate: "2020-02-03",
        buycurrency: "USD",
        buyprice: 125,
        selldate: "2021-05-05",
        sellcurrency: "SGD",
        sellprice: 100,
        playcount: 3,
        },
        {
        name: "Roll Player Adventures",
        buydate: "2021-06-11",
        buycurrency: "SGD",
        buyprice: 203.98,
        selldate: "2022-03-31",
        sellcurrency: "SGD",
        sellprice: 120,
        playcount: 20,
        },
        {
        name: "Sagrada",
        buydate: "2017-05-18",
        buycurrency: "USD",
        buyprice: 40,
        selldate: "2018-07-23",
        sellcurrency: "SGD",
        sellprice: 50,
        playcount: 14,
        },
        {
        name: "Sanctum",
        buydate: "2021-06-10",
        buycurrency: "SGD",
        buyprice: 45.9226,
        selldate: "2021-11-05",
        sellcurrency: "SGD",
        sellprice: 30,
        playcount: 4,
        },
        {
        name: "Scoville",
        buydate: "2018-12-06",
        buycurrency: "SGD",
        buyprice: 57.8,
        selldate: "2019-08-27",
        sellcurrency: "SGD",
        sellprice: 38,
        playcount: 3,
        },
        {
        name: "Scythe",
        buydate: "2018-11-26",
        buycurrency: "SGD",
        buyprice: 67.94,
        selldate: "2019-11-12",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 10,
        },
        {
        name: "Seize the Beans",
        buydate: "2018-02-14",
        buycurrency: "EUR",
        buyprice: 39,
        selldate: "2022-08-08",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 6,
        },
        {
        name: "Sleeping Gods",
        buydate: "2019-09-13",
        buycurrency: "USD",
        buyprice: 131.08,
        selldate: "2021-06-14",
        sellcurrency: "SGD",
        sellprice: 130,
        playcount: 22,
        },
        {
        name: "Small World",
        buydate: "2018-05-04",
        buycurrency: "SGD",
        buyprice: 58,
        selldate: "2018-12-03",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 10,
        },
        {
        name: "Spirit Island",
        buydate: "2018-02-24",
        buycurrency: "USD",
        buyprice: 60.98,
        selldate: "2018-10-29",
        sellcurrency: "SGD",
        sellprice: 80,
        playcount: 10,
        },
        {
        name: "Splendor",
        buydate: "2016-11-14",
        buycurrency: "SGD",
        buyprice: 48,
        selldate: "2017-06-05",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 5,
        },
        {
        name: "Starship Captains",
        buydate: "2022-11-14",
        buycurrency: "EUR",
        buyprice: 59.95,
        selldate: "2023-05-10",
        sellcurrency: "SGD",
        sellprice: 55,
        playcount: 2,
        },
        {
        name: "Streets",
        buydate: "2020-09-28",
        buycurrency: "SGD",
        buyprice: 73.16,
        selldate: "2022-08-11",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 9,
        },
        {
        name: "Stroganov",
        buydate: "2022-02-22",
        buycurrency: "SGD",
        buyprice: 93,
        selldate: "2022-09-19",
        sellcurrency: "SGD",
        sellprice: 55,
        playcount: 3,
        },
        {
        name: "Taiwan",
        buydate: "2019-06-26",
        buycurrency: "TWD",
        buyprice: 1200,
        selldate: "2020-12-15",
        sellcurrency: "SGD",
        sellprice: 15,
        playcount: 2,
        },
        {
        name: "Taluva",
        buydate: "2020-03-27",
        buycurrency: "SGD",
        buyprice: 53.39,
        selldate: "2020-05-31",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 15,
        },
        {
        name: "Tapestry",
        buydate: "2020-10-14",
        buycurrency: "SGD",
        buyprice: 53.32,
        selldate: "2021-07-16",
        sellcurrency: "SGD",
        sellprice: 50,
        playcount: 9,
        },
        {
        name: "Taverns of Tiefenthal",
        buydate: "2021-06-23",
        buycurrency: "SGD",
        buyprice: 54.14,
        selldate: "2022-04-19",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 7,
        },
        {
        name: "The Hunger",
        buydate: "2021-11-13",
        buycurrency: "SGD",
        buyprice: 69.48,
        selldate: "2022-10-31",
        sellcurrency: "SGD",
        sellprice: 35,
        playcount: 6,
        },
        {
        name: "The Networks",
        buydate: "2017-04-30",
        buycurrency: "USD",
        buyprice: 34,
        selldate: "2017-09-12",
        sellcurrency: "SGD",
        sellprice: 38,
        playcount: 2,
        },
        {
        name: "The Reckoners",
        buydate: "2021-04-28",
        buycurrency: "SGD",
        buyprice: 91.82,
        selldate: "2023-01-13",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 12,
        },
        {
        name: "This War of Mine",
        buydate: "2018-02-24",
        buycurrency: "USD",
        buyprice: 69,
        selldate: "2018-07-24",
        sellcurrency: "SGD",
        sellprice: 63,
        playcount: 2,
        },
        {
        name: "Thunderstone Quest",
        buydate: "2018-12-26",
        buycurrency: "SGD",
        buyprice: 120,
        selldate: "2019-09-09",
        sellcurrency: "SGD",
        sellprice: 100,
        playcount: 10,
        },
        {
        name: "Ticket to Ride",
        buydate: "2015-10-15",
        buycurrency: "USD",
        buyprice: 38,
        selldate: "2017-01-15",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 5,
        },
        {
        name: "Tiny Epic Defenders + Dark Wars",
        buydate: "2017-10-19",
        buycurrency: "SGD",
        buyprice: 64.81,
        selldate: "2018-12-21",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 4,
        },
        {
        name: "Tiny Epic Galaxies",
        buydate: "2016-11-28",
        buycurrency: "SGD",
        buyprice: 33,
        selldate: "2017-12-14",
        sellcurrency: "SGD",
        sellprice: 33,
        playcount: 3,
        },
        {
        name: "Tiny Epic Quest",
        buydate: "2017-10-22",
        buycurrency: "SGD",
        buyprice: 38,
        selldate: "2018-08-05",
        sellcurrency: "SGD",
        sellprice: 28,
        playcount: 7,
        },
        {
        name: "Tokaido + Crossroads",
        buydate: "2015-11-15",
        buycurrency: "USD",
        buyprice: 51,
        selldate: "2018-09-02",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 15,
        },
        {
        name: "Tokyo Highway",
        buydate: "2018-08-24",
        buycurrency: "JPY",
        buyprice: 3780,
        selldate: "2019-04-08",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 6,
        },
        {
        name: "Tokyo Highway (4 player)",
        buydate: "2019-02-13",
        buycurrency: "USD",
        buyprice: 42.93,
        selldate: "2020-03-08",
        sellcurrency: "USD",
        sellprice: 42.93,
        playcount: 3,
        },
        {
        name: "Treasure Island",
        buydate: "2021-04-07",
        buycurrency: "SGD",
        buyprice: 15,
        selldate: "2022-02-19",
        sellcurrency: "SGD",
        sellprice: 15,
        playcount: 2,
        },
        {
        name: "Tzolkin",
        buydate: "2018-11-29",
        buycurrency: "SGD",
        buyprice: 54.5,
        selldate: "2020-03-07",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 7,
        },
        {
        name: "Underwater Cities",
        buydate: "2019-08-05",
        buycurrency: "EUR",
        buyprice: 41.99,
        selldate: "2020-05-16",
        sellcurrency: "SGD",
        sellprice: 46.5,
        playcount: 2,
        },
        {
        name: "Villainous",
        buydate: "2018-09-01",
        buycurrency: "SGD",
        buyprice: 48.15,
        selldate: "2018-12-26",
        sellcurrency: "SGD",
        sellprice: 40,
        playcount: 4,
        },
        {
        name: "Vindication",
        buydate: "2021-04-01",
        buycurrency: "SGD",
        buyprice: 100,
        selldate: "2022-10-09",
        sellcurrency: "SGD",
        sellprice: 85,
        playcount: 13,
        },
        {
        name: "Walking in Burano",
        buydate: "2019-06-26",
        buycurrency: "TWD",
        buyprice: 550,
        selldate: "2020-05-20",
        sellcurrency: "SGD",
        sellprice: 17,
        playcount: 8,
        },
        {
        name: "Warhammer Quest Adventure Card Game",
        buydate: "2017-05-18",
        buycurrency: "USD",
        buyprice: 25,
        selldate: "2017-09-26",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 5,
        },
        {
        name: "Yamatai",
        buydate: "2020-06-14",
        buycurrency: "SGD",
        buyprice: 70,
        selldate: "2021-02-19",
        sellcurrency: "SGD",
        sellprice: 45,
        playcount: 5,
        },
        {
        name: "Yokohama",
        buydate: "2018-10-20",
        buycurrency: "JPY",
        buyprice: 5918,
        selldate: "2020-08-14",
        sellcurrency: "SGD",
        sellprice: 25,
        playcount: 11,
        },
        {
        name: "Yokohama Duel",
        buydate: "2020-08-16",
        buycurrency: "SGD",
        buyprice: 88.89,
        selldate: "2022-07-13",
        sellcurrency: "SGD",
        sellprice: 60,
        playcount: 5,
        },
        {
        name: "Zombicide",
        buydate: "2016-05-04",
        buycurrency: "USD",
        buyprice: 58.8,
        selldate: "2016-11-16",
        sellcurrency: "SGD",
        sellprice: 80,
        playcount: 5,
        },
];

export default games;